# Generated by Django 3.1 on 2020-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='ph',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
