# Generated by Django 3.1 on 2020-09-17 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_value_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
