# Generated by Django 3.1 on 2020-09-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_value_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='ph',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='value',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
