# Generated by Django 3.1 on 2020-09-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200922_1130'),
        ('blog', '0006_auto_20200921_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='user',
        ),
        migrations.AddField(
            model_name='value',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
