# Generated by Django 3.1 on 2020-09-22 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20200922_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='user',
        ),
        migrations.AddField(
            model_name='piscina',
            name='n_piscina',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='piscina',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piscina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
